fragment BlogParts on Blog {
  __typename
  viewPostShortcut
  title
  permalink
  description
  seo {
    __typename
    metaTitle
    metaDescription
    ogTitle
    ogDescription
    ogImage
    canonicalUrl
    noindex
    nofollow
  }
  pubDate
  updatedDate
  category {
    ... on Category {
      __typename
      title
      description
    }
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
  author {
    ... on User {
      __typename
      name
      role
      avatar
      bio
      email
    }
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
  heroImage
  authorAlt
  heroImageAlt
  body
}

fragment CategoryParts on Category {
  __typename
  title
  description
}

fragment PageParts on Page {
  __typename
  viewPageShortcut
  title
  permalink
  seo {
    __typename
    metaTitle
    metaDescription
    ogTitle
    ogDescription
    ogImage
    canonicalUrl
    noindex
    nofollow
  }
  blocks {
    __typename
    ... on PageBlocksHomepageTemplate {
      hero {
        __typename
        eyebrow
        title
        description
        buttonText
        buttonLink
        image
        imageAlt
      }
      why {
        __typename
        eyebrow
        title
        paragraphOne
        paragraphTwo
        standards {
          __typename
          label
          title
          text
        }
      }
      newsroom {
        __typename
        heading
        subheading
        submitHeading
        submitButtonText
        submitButtonLink
        prompts {
          __typename
          title
          text
        }
      }
      wireFeature {
        __typename
        eyebrow
        quote
        author
        byline
        image
        imageAlt
      }
      coverage {
        __typename
        title
        description
        topics {
          __typename
          number
          title
          text
        }
      }
      contact {
        __typename
        eyebrow
        title
        description
        note
        cards {
          __typename
          title
          email
          text
          accent
        }
      }
    }
    ... on PageBlocksAboutMockup17 {
      hero {
        __typename
        eyebrow
        headline
        lede
      }
      purpose {
        __typename
        eyebrow
        title
        paragraphOne
        pullquote
        paragraphTwo
      }
      coverage {
        __typename
        eyebrow
        title
        intro
        items {
          __typename
          number
          title
          text
          link
        }
      }
      standardsSection {
        __typename
        eyebrow
        title
        intro
        items {
          __typename
          number
          title
          text
        }
      }
      independence {
        __typename
        eyebrow
        title
        image
        imageAlt
        paragraphOne
        paragraphTwo
        buttonText
        buttonLink
      }
      newsroom {
        __typename
        eyebrow
        title
        intro
        contacts {
          __typename
          icon
          title
          email
          text
        }
      }
    }
    ... on PageBlocksOurTeamMockup17 {
      hero {
        __typename
        eyebrow
        headline
        lede
      }
      leadership {
        __typename
        eyebrow
        title
        people {
          __typename
          name
          role
          location
          image
          imageAlt
          bio
        }
      }
      seniorStaff {
        __typename
        eyebrow
        title
        people {
          __typename
          name
          role
          location
          image
          imageAlt
          bio
        }
      }
    }
    ... on PageBlocksContactMockup17 {
      hero {
        __typename
        eyebrow
        headline
        lede
      }
      formSection {
        __typename
        eyebrow
        title
        description
        buttonText
        note
        formAction
        subject
      }
      inboxes {
        __typename
        eyebrow
        title
        cards {
          __typename
          title
          description
          email
          note
        }
      }
      requests {
        __typename
        eyebrow
        title
        intro
        cards {
          __typename
          icon
          title
          text
        }
      }
    }
    ... on PageBlocksHero {
      headline
      tagline
      actions {
        __typename
        label
        type
        icon
        link
      }
      image {
        __typename
        src
        alt
      }
      starfield
    }
    ... on PageBlocksCallout {
      text
      url
    }
    ... on PageBlocksFeatures {
      title
      description
      items {
        __typename
        icon
        title
        text
      }
    }
    ... on PageBlocksStats {
      title
      description
      stats {
        __typename
        stat
        type
      }
    }
    ... on PageBlocksCta {
      title
      description
      actions {
        __typename
        label
        type
        icon
        link
      }
    }
    ... on PageBlocksContent {
      body
    }
    ... on PageBlocksTestimonial {
      title
      description
      testimonials {
        __typename
        quote
        author
        role
        avatar
      }
    }
    ... on PageBlocksVideo {
      url
      autoPlay
      loop
    }
    ... on PageBlocksSplit {
      title
      body
      image {
        __typename
        src
        alt
      }
      reverse
      actions {
        __typename
        label
        type
        icon
        link
      }
    }
  }
}

fragment UserParts on User {
  __typename
  name
  role
  avatar
  bio
  email
}

fragment NavigationParts on Navigation {
  __typename
  title
  items {
    __typename
    label
    href
    children {
      __typename
      label
      href
    }
  }
}

fragment ConfigParts on Config {
  __typename
  seo {
    __typename
    title
    description
    siteOwner
    logo
    footerLogo
  }
  contactForm {
    __typename
    formspreeEndpoint
    heading
    description
    buttonText
    note
    subject
  }
  codeInjection {
    __typename
    headerCode
    footerCode
  }
  contactLinks {
    __typename
    title
    link
    icon
  }
  footerStarfield
}
