export const aboutMockup17BlockSchema = {
  name: 'aboutMockup17',
  label: 'About Page - Mockup 17',
  fields: [
    { name: 'eyebrow', label: 'Hero Eyebrow', type: 'string' },
    { name: 'headline', label: 'Hero Headline', type: 'string' },
    { name: 'lede', label: 'Hero Lede', type: 'string', ui: { component: 'textarea' } },
    { name: 'purposeEyebrow', label: 'Purpose Eyebrow', type: 'string' },
    { name: 'purposeTitle', label: 'Purpose Title', type: 'string' },
    { name: 'purposeParagraphOne', label: 'Purpose Paragraph 1', type: 'string', ui: { component: 'textarea' } },
    { name: 'purposePullquote', label: 'Purpose Pullquote', type: 'string', ui: { component: 'textarea' } },
    { name: 'purposeParagraphTwo', label: 'Purpose Paragraph 2', type: 'string', ui: { component: 'textarea' } },
    { name: 'coverageEyebrow', label: 'Coverage Eyebrow', type: 'string' },
    { name: 'coverageTitle', label: 'Coverage Title', type: 'string' },
    { name: 'coverageIntro', label: 'Coverage Intro', type: 'string', ui: { component: 'textarea' } },
    { name: 'coverageItems', label: 'Coverage Cards', type: 'object', list: true, fields: [{ name: 'number', label: 'Number', type: 'string' }, { name: 'title', label: 'Title', type: 'string' }, { name: 'text', label: 'Text', type: 'string', ui: { component: 'textarea' } }, { name: 'link', label: 'Link', type: 'string' }] },
    { name: 'standardsEyebrow', label: 'Standards Eyebrow', type: 'string' },
    { name: 'standardsTitle', label: 'Standards Title', type: 'string' },
    { name: 'standardsIntro', label: 'Standards Intro', type: 'string', ui: { component: 'textarea' } },
    { name: 'standards', label: 'Standards Rows', type: 'object', list: true, fields: [{ name: 'number', label: 'Number', type: 'string' }, { name: 'title', label: 'Title', type: 'string' }, { name: 'text', label: 'Text', type: 'string', ui: { component: 'textarea' } }] },
    { name: 'independenceEyebrow', label: 'Independence Eyebrow', type: 'string' },
    { name: 'independenceTitle', label: 'Independence Title', type: 'string' },
    { name: 'independenceImage', label: 'Independence Image', type: 'image' },
    { name: 'independenceImageAlt', label: 'Independence Image Alt Text', type: 'string' },
    { name: 'independenceParagraphOne', label: 'Independence Paragraph 1', type: 'string', ui: { component: 'textarea' } },
    { name: 'independenceParagraphTwo', label: 'Independence Paragraph 2', type: 'string', ui: { component: 'textarea' } },
    { name: 'independenceButtonText', label: 'Independence Button Text', type: 'string' },
    { name: 'independenceButtonLink', label: 'Independence Button Link', type: 'string' },
    { name: 'newsroomEyebrow', label: 'Newsroom Eyebrow', type: 'string' },
    { name: 'newsroomTitle', label: 'Newsroom Title', type: 'string' },
    { name: 'newsroomIntro', label: 'Newsroom Intro', type: 'string', ui: { component: 'textarea' } },
    { name: 'contacts', label: 'Contact Cards', type: 'object', list: true, fields: [{ name: 'icon', label: 'Icon', type: 'string', options: ['chat', 'alert', 'document'] }, { name: 'title', label: 'Title', type: 'string' }, { name: 'email', label: 'Email', type: 'string' }, { name: 'text', label: 'Text', type: 'string', ui: { component: 'textarea' } }] },
  ],
};
