export const homepageTemplateBlockSchema = {
  name: 'homepageTemplate',
  label: 'Homepage Template Content',
  fields: [
        {
          type: 'object',
          name: 'hero',
          label: 'Hero Section',
          fields: [
            { name: 'eyebrow', label: 'Eyebrow', type: 'string' },
            { name: 'title', label: 'Headline', type: 'string' },
            { name: 'description', label: 'Description', type: 'string', ui: { component: 'textarea' } },
            { name: 'buttonText', label: 'Button Text', type: 'string' },
            { name: 'buttonLink', label: 'Button Link', type: 'string' },
            { name: 'image', label: 'Hero Image', type: 'image' },
            { name: 'imageAlt', label: 'Hero Image Alt Text', type: 'string' },
          ],
        },
        {
          type: 'object',
          name: 'why',
          label: 'Why / Editorial Standards Section',
          fields: [
            { name: 'eyebrow', label: 'Eyebrow', type: 'string' },
            { name: 'title', label: 'Heading', type: 'string' },
            { name: 'paragraphOne', label: 'Paragraph 1', type: 'string', ui: { component: 'textarea' } },
            { name: 'paragraphTwo', label: 'Paragraph 2', type: 'string', ui: { component: 'textarea' } },
            {
              type: 'object',
              list: true,
              name: 'standards',
              label: 'Standards Cards',
              fields: [
                { name: 'label', label: 'Small Label', type: 'string' },
                { name: 'title', label: 'Card Title', type: 'string' },
                { name: 'text', label: 'Card Text', type: 'string', ui: { component: 'textarea' } },
              ],
            },
          ],
        },
        {
          type: 'object',
          name: 'newsroom',
          label: 'Latest Newsroom / Submit Panel',
          fields: [
            { name: 'heading', label: 'Latest News Heading', type: 'string' },
            { name: 'subheading', label: 'Latest News Subheading', type: 'string' },
            { name: 'submitHeading', label: 'Submit Panel Heading', type: 'string' },
            { name: 'submitButtonText', label: 'Submit Button Text', type: 'string' },
            { name: 'submitButtonLink', label: 'Submit Button Link', type: 'string' },
            {
              type: 'object',
              list: true,
              name: 'prompts',
              label: 'Submit Prompt Items',
              fields: [
                { name: 'title', label: 'Title', type: 'string' },
                { name: 'text', label: 'Text', type: 'string', ui: { component: 'textarea' } },
              ],
            },
          ],
        },
        {
          type: 'object',
          name: 'wireFeature',
          label: 'From the Wire Feature',
          fields: [
            { name: 'eyebrow', label: 'Eyebrow', type: 'string' },
            { name: 'quote', label: 'Quote', type: 'string', ui: { component: 'textarea' } },
            { name: 'author', label: 'Author Name', type: 'string' },
            { name: 'byline', label: 'Byline', type: 'string' },
            { name: 'image', label: 'Feature Image', type: 'image' },
            { name: 'imageAlt', label: 'Feature Image Alt Text', type: 'string' },
          ],
        },
        {
          type: 'object',
          name: 'coverage',
          label: 'What We Cover Section',
          fields: [
            { name: 'title', label: 'Heading', type: 'string' },
            { name: 'description', label: 'Description', type: 'string', ui: { component: 'textarea' } },
            {
              type: 'object',
              list: true,
              name: 'topics',
              label: 'Coverage Topic Cards',
              fields: [
                { name: 'number', label: 'Number', type: 'string' },
                { name: 'title', label: 'Topic Title', type: 'string' },
                { name: 'text', label: 'Topic Text', type: 'string', ui: { component: 'textarea' } },
              ],
            },
          ],
        },
        {
          type: 'object',
          name: 'contact',
          label: 'Get In Touch Section',
          fields: [
            { name: 'eyebrow', label: 'Eyebrow', type: 'string' },
            { name: 'title', label: 'Heading', type: 'string' },
            { name: 'description', label: 'Description', type: 'string', ui: { component: 'textarea' } },
            { name: 'note', label: 'Note', type: 'string', ui: { component: 'textarea' } },
            {
              type: 'object',
              list: true,
              name: 'cards',
              label: 'Contact Cards',
              fields: [
                { name: 'title', label: 'Card Title', type: 'string' },
                { name: 'email', label: 'Email', type: 'string' },
                { name: 'text', label: 'Card Text', type: 'string', ui: { component: 'textarea' } },
                { name: 'accent', label: 'Accent Card', type: 'boolean' },
              ],
            },
          ],
        },
      ],
};
